# Generated by Django 5.1.7 on 2025-05-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="session_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("student", "session_id")},
        ),
    ]
